version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    volumes:
      -  ./data/:/data/db
  # development only
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081