version: "3"
services: 
    # hbase:
    #     image: hyness/hbase-rest-standalone 
    #     # image: harisekhon/hbase:1.2
    #     volumes:
    #         - ./docker_volumes/hbase/hbase-server-config.xml:/opt/hbase/conf/hbase-site.xml
    #         # - ./docker_volumes/hbase/hbase-server-config.xml:/hbase/conf/hbase-site.xml
    #         - ./docker_volumes/hbase/hbase-data/:/data/hbase
    #         - ./docker_volumes/hbase/zookeeper-data/:/data/zookeeper
    #     hostname: hbase
    
    elasticsearch:
        image: elasticsearch:5.5.2
        hostname: elasticsearch
        command: [elasticsearch, -Ecluster.name=elasticsearch, -Ediscovery.zen.ping.unicast.hosts=elasticsearch] 
    pio:
        build: 
            context: ./prediction.io
            dockerfile: Dockerfile-0.12
        # command: bash -c 'echo "sleeping for 30 seconds" && sleep 30 && pio eventserver'
        command: bash -c 'echo "sleeping for 30 seconds" && /prediction-io/vendors/hbase/bin/hbase --config /prediction-io/vendors/hbase/conf master start && pio eventserver'
        ports:
            - "7070:7070"
        volumes:
            - ./docker_volumes/prediction-io-store:/prediction-io/.pio_store
            # - ./docker_volumes/hbase/hbase-client-config.xml:/prediction-io/vendors/hbase/conf/hbase-site.xml
            - ./docker_volumes/hbase/hbase-site.xml:/prediction-io/vendors/hbase/conf/hbase-site.xml
            - ./docker_volumes/hbase/hbase-data/:/prediction-io/vendors/hbase/data
            - ./docker_volumes/hbase/zookeeper-data/:/prediction-io/vendors/hbase/zookeeper
            - ./docker_volumes/hbase/hbase-env.sh:/prediction-io/vendors/hbase/conf/hbase-env.sh
            - ./docker_volumes/universal/:/prediction-io/universal
            - ./docker_volumes/pio-env.sh:/prediction-io/conf/pio-env.sh