version: "3"
services:
  de-namenode:
    image: uhopper/hadoop-namenode:2.7.2
    container_name: de-namenode
    ports:
      - 8020:8020
      - 8084:50070
    volumes:
      - ./hadoop/name:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=DE_HADOOP_MASTER
  de-datanode-1:
    image: uhopper/hadoop-datanode:2.7.2
    container_name: de-datanode1
    volumes:
      - ./hadoop/data:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://de-namenode:8020
  de-resourcemanager:
    image: uhopper/hadoop-resourcemanager:2.7.2
    container_name: de-resourcemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://de-namenode:8020
      - YARN_CONF_yarn_log___aggregation___enable=true
  de-nodemanager-1:
    image: uhopper/hadoop-nodemanager:2.7.2
    container_name: de-nodemanager
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://de-namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=de-resourcemanager
      - YARN_CONF_yarn_log___aggregation___enable=true
      - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs
  de-spark-1:
    image: uhopper/hadoop-spark:2.1.2_2.8.1
    container_name: de-spark
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://de-namenode:8020
      - YARN_CONF_yarn_resourcemanager_hostname=de-resourcemanager
    command: tail -f /var/log/dmesg
  
  de-hbase-1:
    image: harisekhon/hbase:1.2
    container_name: de-hbase
    volumes:
        - ./hbase/hbase-server-config.xml:/opt/hbase/conf/hbase-site.xml
        - ./hbase/hbase-data/:/data/hbase
        - ./hbase/zookeeper-data/:/data/zookeeper
    ports:
        - 8100:16000
        - 8101:16010
        - 8102:16020
        - 8103:16030
        - 8104:2888
        - 8105:3888
        - 8106:2181
  de-elasticsearch:
    image: elasticsearch:5.5.2
    container_name: de-elasticsearch
    command: [elasticsearch, -Ecluster.name=de-elasticsearch, -Ediscovery.zen.ping.unicast.hosts=de-elasticsearch]
  de-pio:
    image: decision-prediction:1.0
    container_name: de-prediction
    command: bash -c 'echo "sleeping for 30 seconds" && pio eventserver'
    ports: 
      - 7071:7070
    volumes:
      - ./prediction/volumes/hadoop/:/etc/hadoop
      - ./prediction/volumes/prediction-io-store:/prediction-io/.pio_store
      - ./prediction/volumes/hbase/hbase-client-config.xml:/prediction-io/vendors/hbase/conf/hbase-site.xml
      - ./prediction/volumes/hbase/hbase-data/:/prediction-io/vendors/hbase/data
      - ./prediction/volumes/hbase/zookeeper-data/:/prediction-io/vendors/hbase/zookeeper
      - ./prediction/volumes/hbase/hbase-env.sh:/prediction-io/vendors/hbase/conf/hbase-env.sh
      - ./prediction/volumes/universal/:/prediction-io/universal
      - ./prediction/volumes/pio-env.sh:/prediction-io/conf/pio-env.sh